version: '3'
services:
  web:
    container_name: api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - .:/api
    links:
      - db
  db:
    container_name: mongoapi
    image: mongo:4.1
    volumes:
      - ./db_data:/data/db