version: '3'
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/api
    links:
      - db
  db:
    container_name: mongoapi
    image: mongo:4.1
    volumes:
      - ./db_data:/data/db
  ui:
    container_name: webui
    image: thesisui:0.1
    ports:
      - "80:80"
    links:
      - api