#! /bin/bash

if [ $1 = 'up' ]; 
then
    sudo docker-compose down && sudo docker-compose up -d 
fi

if [ $1 = 'down' ]; 
then
    docker-compose down
fi

if [ $1 = 'ps' ]; 
then
    docker-compose ps
fi

if [ $1 = 'logs' ]; 
then
    docker logs api && echo -e "\n\n\n" && docker logs mongoapi  
fi